# # Uncomment the following if you want to fetch the pro packages from the private registry.
# # Make sure you also update the `workspace:*` ranges for all pro dependencies to their latest version.
# # @see https://saas-ui.dev/docs/pro/installation/yarn
#
# npmScopes:
#   saas-ui-pro:
#     npmRegistryServer: 'https://npm.saas-ui.dev'
# npmRegistries:
#   //npm.saas-ui.dev:
#     npmAuthIdent: '${SAAS_UI_TOKEN:-}'
#     npmAlwaysAuth: true

# checksumBehavior: update

# We use node-modules linker to avoid issues with Yarn PnP and ESM packages.
nodeLinker: node-modules

packageExtensions:
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  'recharts@*':
    dependencies:
      'prop-types': '*'
  '@tiptap/starter-kit@*':
    peerDependencies:
      '@tiptap/pm': '*'
      'prosemirror-commands': '*'
      'prosemirror-dropcursor': '*'
      'prosemirror-gapcursor': '*'
      'prosemirror-history': '*'
      'prosemirror-keymap': '*'
      'prosemirror-model': '*'
      'prosemirror-schema-list': '*'
      'prosemirror-state': '*'
      'prosemirror-transform': '*'
      'prosemirror-view': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
